on:
  push:
    branches:
      - main

name: Build My Apps

jobs:
  build:
    name: Build and Release APKs
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v3

      # Java 17
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      # Cache Gradle
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Permiso a gradlew
      - name: Make Gradlew Executable
        run: chmod +x ./gradlew

      # Build APK Debug
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Verify Debug APK
        run: ls -l app/build/outputs/apk/debug/

      - name: Push Debug APK to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "app/build/outputs/apk/debug/app-debug.apk"
          tag: latest
          name: Latest-Release
          replacesArtifacts: true
          allowUpdates: true
          token: ${{ secrets.TOKEN }}

      # Build APK Release
      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Verify Release APK
        run: ls -l app/build/outputs/apk/release/

      # Firmar APK
      - name: Decode keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > keystore.jks

      - name: Sign APK
        run: |
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
            -keystore keystore.jks -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
            -keypass ${{ secrets.KEY_PASSWORD }} \
            app/build/outputs/apk/release/app-release-unsigned.apk ${{ secrets.KEY_ALIAS }}

      - name: Zipalign APK
        run: |
          sudo apt-get update && sudo apt-get install -y zipalign
          zipalign -v 4 app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/app-release.apk

      # Subir APK firmado
      - name: Push Signed Release APK to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "app/build/outputs/apk/release/app-release.apk"
          tag: latest
          name: Latest-Release
          replacesArtifacts: true
          allowUpdates: true
          token: ${{ secrets.TOKEN }}
