on:
  push:
    branches:
      - main

name: Build My Apps

jobs:
  build:
    name: Build and Release new apk
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Set up Java 17
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      
      # Cache Gradle dependencies
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      
      # Grant execute permissions to the Gradle wrapper
      - name: Make Gradlew Executable
        run: chmod +x ./gradlew

      # Build the debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # Verify the debug APK exists
      - name: Verify Debug APK
        run: ls -l app/build/outputs/apk/debug/

      # Upload the debug APK to GitHub Releases
      - name: Push Debug APK to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "app/build/outputs/apk/debug/*.apk"
          tag: debug-v0.0.3
          token: ${{ secrets.TOKEN }}

      # # Build the release APK
      # - name: Build Release APK
      #   run: ./gradlew assembleRelease

      # # Verify the release APK exists
      # - name: Verify Release APK
      #   run: ls -l app/build/outputs/apk/release/

      # # Upload the release APK to GitHub Releases
      # - name: Push Release APK to Releases
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "app/build/outputs/apk/release/*.apk"
      #     tag: release-v0.0.2
      #     token: ${{ secrets.TOKEN }}